#cloud-config
hostname: ${runner_name}
users:
  - name: runner
    groups: [adm, sudo, docker]
    lock-passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCXkppxm/2pXDfEadUaUGdKBPLnSpFbcJkEmndthYWpCHXOmO0hK8tD3WFxWgVOZPlrqpVsSzJ6Cabj19yuxoWskUayuQ+5bc5BZz6NhoL/lJsqBLGDqZ5h7NspjjTat/AI/Nzb8K3ZNmD3SKpKDSbyqg0K6LGfAHV/agjUjS60dEaYJXX57yVq1zcydwEXb6nF95bxcGIjVfmlXL8dx4efD8kNCX0ITlHLaKo3ZzX5DwOEGFB8DqpUaY8pZ+dxPoATsgyBMjrqftP4dOxLlSkwluZnb0/SY8c3pfOQIjBJX0mhdYpvV4ZGxNa/G2+nUuMZT3WydJ87BetK8I/nN7uDD5gUpl/w002Z8HfVhuWLzOc09p9ySuKXBvDMDseIKQgG9QiYNbOuEz57njBkPS4R4bkXfOlufCVruQ+6JhmnWOvILpgwYFuE1SSuauhOI9iy/VjnD/org/J6m+JmAQKkl0MUohR8S5nfi7rfHPxM+nhgbw3t1v7FQGuGE3g/ons= rob@greenteeth

runcmd:
    - cd /home/runner
    - mkdir actions-runner && cd actions-runner
    - curl -o actions-runner-linux-x64-${runner_version}.tar.gz -L https://github.com/actions/runner/releases/download/v2.322.0/actions-runner-linux-x64-${runner_version}.tar.gz
    - tar -xzf ./actions-runner-linux-x64-${runner_version}.tar.gz
    - su - runner -c "./actions-runner/config.sh --url https://github.com/${runner_org} --token ${runner_token} --unattended"
    - ./svc.sh install runner
    - ./svc.sh start
    - ./svc.sh status
